### ISSUE TITLE
Error when calculating protein groups

### ISSUE THREAD

**Issue by silasmellor** [mgerault/DIAgui#1]
Hey there, firstly let me just say its super nice to have this available to process DIA-NN outputs further. I am getting an error running the protein groups calculations.

The error says "error in [.data.frame: undefined columns selected"

I am processing data for a non-uniprot proteome, so i dont know if that may cause any issues?

Calculation...
Concatenating secondary ids...

Removing low intensities...

Concatenating secondary ids...

Removing low intensities...

nrow = 925646, # proteins = 10377, # samples = 15
11 thread(s) available...
9%
14%
20%
25%
30%
35%
40%
67%
72%
77%
82%
Completed.
Warning: Error in [.data.frame: udefinerede kolonner valgt
  2: shiny::runApp
  1: runDIAgui

**Comment by mgerault** [comment]
Well, in this function, it's looking for the peptide sequence from the given identifier, i.e. the protein ID; which is after 'sp' in a classic FASTA files like : 'sp|O15263|DFB4A_HUMAN Defensin beta 4A OS=Homo sapiens OX=9606 GN=DEFB4B PE=1 SV=1'.

So in order to work, the IDs in your report files must be 'Peinf101Ctg12185235g00001' and it needs to have a peptide sequence attached. If it's not the case it will render a NULL result and this could be why you had the error "error in [.data.frame: undefined columns selected". 
Maybe you can try to run the function 'getallseq' like this : 
getallseq(pr_id = "Peinf101Ctg12185235g00001", bank_name = "path/to_your/FATSA_file.fasta", fasta_file = TRUE)
If it returns an empty list, it means that your FASTA file doesn't contain 'Peinf101Ctg12185235g00001' or any peptide sequence.

**Comment by silasmellor** [comment]
Ok flipping the IDs around did no difference. I also checked the report.tsv for the in silico and it already appears to follow the nomenclature i used for the pseudo uniprot headers, so it should be able to find the sequence.

Here are a few lines from my report.tsv
File.Name	Run	Protein.Group	Protein.Ids	Protein.Names	Genes	PG.Quantity	PG.Normalised	PG.MaxLFQ	Genes.Quantity	Genes.Normalised	Genes.MaxLFQ	Genes.MaxLFQ.Unique	Modified.Sequence	Stripped.Sequence	Precursor.Id	Precursor.Charge	Q.Value	PEP	Global.Q.Value	Protein.Q.Value	PG.Q.Value	Global.PG.Q.Value	GG.Q.Value	Translated.Q.Value	Proteotypic	Precursor.Quantity	Precursor.Normalised	Precursor.Translated	Ms1.Translated	Quantity.Quality	RT	RT.Start	RT.Stop	iRT	Predicted.RT	Predicted.iRT	Lib.Q.Value	Lib.PG.Q.Value	Ms1.Profile.Corr	Ms1.Area	Evidence	Spectrum.Similarity	Mass.Evidence	CScore	Decoy.Evidence	Decoy.CScore	Fragment.Quant.Raw	Fragment.Quant.Corrected	Fragment.Correlations	MS2.Scan	PTM.Informative	PTM.Specific	PTM.Localising	PTM.Q.Value	PTM.Site.Confidence	Lib.PTM.Site.Confidence	IM	iIM	Predicted.IM	Predicted.iIM
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S1_A1_1_754.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S1_A1_1_754	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		8940.79	5863.08	5972.03					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	5.41922e-06	5.41922e-06	0.00040962	0.000166834	0.000128584	0.000112587	1	0	1	4197.99	3001.62	2988.23	16937.3	0.858255	47.2871	47.1066	47.4676	17.9993	47.2198	18.0655	1.36662e-05	0.000118737	0.98298	23794.3	3.37404	0.524575	1.97965	0.999995	0.202491	0.0865911	335.004;2233.03;2667.03;235.003;1134.01;169.002;306.004;85.0013;79.0009;1446.02;24.0003;514.006;	132.249;1398.71;2667.03;125.717;423.507;0;69.5741;44.5467;0;1313.96;0;274.15;	0.343245;0.687918;0.973125;0.527147;0.658646;0.429175;0.493312;0.513013;0.276535;0.836568;0.325577;0.496118;	50317	1.97965	0	0	0	0.999986	0.999986	1.18375	1.17917	1.17317	1.18952
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S2_A2_1_755.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S2_A2_1_755	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		4251.17	3823.71	5498.33					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	3.56205e-07	3.56205e-07	0.00040962	0.000151745	0.000139392	0.000112587	1	0	1	2288.69	1929.83	1584.65	14239.7	0.826234	47.2561	47.0757	47.4366	17.9993	47.2655	17.9952	1.36662e-05	0.000118737	0.957017	20566.2	3.05359	0.391675	1.73559	1	0.579776	0.0402674	335.004;1558.02;1960.03;118.001;982.012;224.003;91.0013;20.0003;155.002;1392.02;182.002;324.003;	335.004;206.323;1747.37;47.8804;321.091;31.7505;0;0;24.9869;937.868;29.7265;138.995;	0.93842;0.485742;0.84493;0.552463;0.573429;0.126918;0.216506;0.292344;0.214586;0.791368;0.152452;0.446295;	50285	1.73559	0	0	0	0.999986	0.999986	1.17542	1.17917	1.17664	1.17772
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S3_A3_1_756.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S3_A3_1_756	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		5449.13	4470.99	5379.53					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	1.93252e-05	1.93252e-05	0.00040962	0.00014622	0.00011868	0.000112587	1	0	1	4174.99	3287.79	3130.64	12878.9	0.905322	47.9127	47.7323	48.093	17.9993	47.8431	18.0871	1.36662e-05	0.000118737	0.963982	17175.2	3.02061	0.272235	1.55414	0.999981	1.21377	0.0925954	292.003;1591.02;2532.03;230.002;627.008;210.002;177.002;129.001;52.0005;1327.02;243.003;498.006;	88.0371;1554.93;2532.03;82.3925;0;0;0;0;0;443.128;66.7102;298.615;	0.274584;0.860657;0.954682;0.401904;0.278975;0.201656;0.266781;0.394335;-0.494482;0.727248;0.0796454;0.549992;	50989	1.55414	0	0	0	0.999981	0.999986	1.18042	1.17917	1.17816	1.1808
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S4_A4_1_757.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S4_A4_1_757	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		7649.86	6526.45	6118.1					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	1.05127e-05	1.05127e-05	0.00040962	0.000132135	9.75134e-05	0.000112587	1	0	1	4035.51	2832.16	3337.54	12671.3	0.87437	47.9714	47.7911	48.1516	17.9993	47.9313	18.0591	1.36662e-05	0.000118737	0.987454	15321.2	3.10823	0.243199	0.881703	0.99999	0.535129	0.0190418	282.003;1615.02;2361.03;165.002;892.01;87.001;74.0008;23.0003;112.001;618.006;143.002;218.002;	106.482;1568;2361.03;0;322.618;25.2657;0;0;52.7476;239.373;0;0;	0.598506;0.812744;0.927739;-0.0919049;0.551916;0.580016;-0.377553;0.168163;0.444264;0.621942;0.369484;0.641407;	51053	0.881703	0	0	0	0.999986	0.999986	1.18	1.17917	1.17655	1.18239
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S5_A5_1_758.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S5_A5_1_758	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		6806.46	5280.24	5017.32					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	1e-09	0	0.00040962	0.000143637	0.000106895	0.000112587	1	0	1	4964.96	3742.84	3911.53	14538.7	0.853554	47.876	47.6958	48.0563	17.9993	47.897	17.9833	1.36662e-05	0.000118737	0.964347	18454.2	3.54161	0.57002	1.41632	1	0	-1e+07	694.008;1862.02;2900.04;164.002;910.01;152.002;240.003;53.0005;53.0005;1469.02;166.002;218.002;	491.679;1862.02;2611.26;98.6924;0;52.9467;55.7146;0;0;1086.92;87.2743;105.039;	0.791379;0.925151;0.814208;0.700861;0.322591;0.46503;0.262122;-0.255739;0.513181;0.673555;0.634936;0.359871;	50957	1.41632	0	0	0	0.999986	0.999986	1.18083	1.17917	1.175	1.18455
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S6_A6_1_759.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S6_A6_1_759	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		3425.82	3220.32	4457.89					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	7.71942e-05	0.000204081	0.00040962	0.000153445	0.000115181	0.000112587	1	0	1	1958.17	1752.89	1746.57	10317.2	0.774518	48.055	47.8747	48.2353	17.9993	48.0759	17.9698	1.36662e-05	0.000118737	0.882699	11567.1	1.42803	0.392801	1.07534	0.999798	0.770951	0.0661442	316.003;852.009;1448.02;62.0008;305.004;55.0006;57.0005;71.0008;65.0008;1032.01;24.0003;281.003;	75.6812;434.468;1448.02;0;80.9681;24.526;0;0;0;500.595;0;111.513;	0.411383;0.42564;0.898177;0.32555;0.37956;0.370729;0.1311;0.0235057;0.00596034;0.592511;0.281337;0.221755;	51149	1.07534	0	0	0	0.999796	0.999986	1.18792	1.17917	1.17644	1.19047
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S7_A7_1_760.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S7_A7_1_760	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		5456.7	4937.85	4386.36					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	6.17546e-06	6.17546e-06	0.00040962	0.000150921	0.000113058	0.000112587	1	0	1	1475.14	1260.86	1325.55	10330.3	0.697457	48.0221	47.8418	48.2024	17.9993	48.0255	17.9799	1.36662e-05	0.000118737	0.953791	11496.1	2.66577	0.613044	1.14632	0.999994	0.552994	0.0853206	278.003;715.009;1105.01;121.002;301.003;0;257.003;38.0004;61.0008;264.004;32.0004;269.003;	147.46;715.009;612.673;50.0661;160.337;0;44.0653;35.9319;0;48.8398;0;50.3406;	0.428136;0.875468;0.554534;0.580388;0.697213;0;-0.089272;0.810248;-0.141842;0.191101;0.272058;0.332995;	51117	1.14632	0	0	0	0.999986	0.999986	1.18409	1.17917	1.1765	1.1866
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S8_A8_1_761.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S8_A8_1_761	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		6610.35	5820.81	5092.47					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	4.79602e-07	4.79602e-07	0.00040962	0.000144092	0.000127486	0.000112587	1	0	1	3787.07	3323.2	3088.82	12957.9	0.862112	48.111	47.9307	48.2913	17.9993	48.0806	18.0359	1.36662e-05	0.000118737	0.96121	15887.2	2.85431	0.43106	0.91919	1	0.636904	0.0727274	253.003;1829.02;1951.02;109.001;542.006;189.002;63.0006;84.001;84.0008;642.007;150.002;330.004;	88.9449;1747.1;1951.02;0;130.85;40.0205;29.8563;0;0;76.6433;0;54.1546;	0.666412;0.847118;0.884461;0.47653;0.412369;0.217765;0.51074;0.0836896;0.364866;-0.298736;0.0565258;-0.178095;	51213	0.91919	0	0	0	0.999986	0.999986	1.18667	1.17917	1.18266	1.18288
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S9_A9_1_762.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S9_A9_1_762	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		4289.64	5379.83	4367.27					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	2.73583e-05	4.2056e-05	0.00040962	0.000159084	0.00011936	0.000112587	1	0	1	775.18	987.659	803.969	8897.72	0.791239	48.561	48.3806	48.7413	17.9993	48.6268	17.9097	1.36662e-05	0.000118737	0.949942	8579.11	1.88337	0.330599	0.317543	0.999959	1.07026	0.148039	251.003;643.008;1040.01;201.002;273.003;120.002;128.002;0;39.0004;323.003;56.0007;245.003;	0;643.008;132.173;56.9956;0;39.8401;32.5562;0;0;0;25.2615;80.911;	0.425125;0.882768;0.345959;0.572408;0.448072;0.404219;0.310897;0;0.456605;0.104892;0.500916;0.370444;	51693	0.317543	0	0	0	0.999958	0.999986	1.19455	1.17917	1.18438	1.18883
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S10_A10_1_763.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S10_A10_1_763	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		12159.9	7709.12	5291.5					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	3.01392e-06	3.01392e-06	0.00040962	0.000146177	0.000109254	0.000112587	1	0	1	3234.13	2537.67	3124.13	17676.8	0.744032	48.2811	48.1009	48.4614	17.9993	48.3346	17.9584	1.36662e-05	0.000118737	0.925104	18299.2	2.80603	0.478539	1.48946	0.999997	1.49471	0.234135	285.004;1564.02;2153.02;158.002;821.011;118.002;109.001;58.0007;181.002;903.009;100.001;435.005;	57.1918;1564.02;1612.91;108.832;119.085;0;0;7.42218;115.945;581.216;30.6033;54.7416;	0.247696;0.881093;0.628725;0.720552;0.258758;0.0647556;0.0368994;0.0649089;0.462457;0.765347;0.313892;0.393237;	51405	1.48946	0	0	0	0.999986	0.999986	1.2	1.17917	1.19172	1.18741
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S11_A11_1_764.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S11_A11_1_764	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		5287.19	5399.57	4955.08					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	2.48139e-05	3.10491e-05	0.00040962	0.000164366	0.000125125	0.000112587	1	0	1	3209.43	3362.03	3514.69	19257.8	0.811093	48.2812	48.1009	48.4615	17.9993	48.3016	17.9677	1.36662e-05	0.000118737	0.97221	17585.2	2.86328	0.405383	1.71054	0.999969	0.535129	0.071513	162.002;1851.02;2473.03;65.0008;594.008;256.003;218.002;87.0011;186.003;952.012;127.001;449.005;	34.0478;1851.02;1324.36;0;382.492;71.481;0;51.4341;77.7614;630.691;47.254;35.3718;	0.108413;0.897109;0.708938;0.309377;0.623417;0.159985;-0.0622042;0.718747;0.140758;0.429493;0.0888376;0.459571;	51405	1.71054	0	0	0	0.999969	0.999986	1.20042	1.17917	1.19313	1.18547
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S12_A12_1_765.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S12_A12_1_765	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		10157.5	7309.97	4759.04					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	0.000135093	0.000172162	0.00040962	0.000146628	0.000109469	0.000112587	1	0	1	3001.22	2433.74	2745.89	13318.7	0.915568	48.1903	48.01	48.3706	17.9993	48.2421	17.948	1.36662e-05	0.000118737	0.965135	14557.2	2.89316	0.169945	0.231672	0.99983	0.299928	0.0369042	414.006;1384.02;1716.02;87.0012;505.006;108.001;248.004;10.0001;59.0008;786.01;115.002;393.004;	61.5045;1223.69;1716.02;0;0;8.22119;76.1315;0;4.82449;126.595;17.893;0;	0.117088;0.890409;0.962128;-0.232322;0.320817;-0.0520381;0.562227;-0.00567443;-0.0404841;0.476452;0.14833;0.523916;	51309	0.231672	0	0	0	0.999828	0.999986	1.2	1.17917	1.19918	1.17959
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S13_B1_1_766.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S13_B1_1_766	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		2711.97	2633.53	4203.18					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	5.54047e-05	0.00018525	0.00040962	0.000140944	0.000109505	0.000112587	1	0	1	713.908	704.733	632.586	9158.74	0.488477	48.4026	48.2223	48.5828	17.9993	48.3676	18.0301	1.36662e-05	0.000118737	0.727157	10336.1	2.3819	0.508871	0.617349	0.999815	0	-1e+07	140.002;823.01;714.009;32.0004;367.004;154.002;135.002;0;57.0005;363.004;139.002;179.002;	140.002;250.767;323.139;12.2397;75.7277;46.7453;29.2165;0;0;0;0;43.0057;	0.852822;0.430234;0.375821;0.6402;0.20308;0.577055;0.459721;0;-0.274711;0.21072;-0.0096748;0.402305;	51533	0.617349	0	0	0	0.999815	0.999986	1.20542	1.17917	1.20016	1.18347
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S14_B2_1_767.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S14_B2_1_767	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		7018.48	6003.88	5511.81					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	1.62972e-05	1.62972e-05	0.00040962	0.000190512	0.000149858	0.000112587	1	0	1	3087.09	2788.46	2810.59	16068.5	0.806497	48.6109	48.4307	48.7912	17.9993	48.6557	17.9416	1.36662e-05	0.000118737	0.954254	17649.2	3.07067	0.276327	1.09916	0.999984	0.535129	0.0484055	307.004;1331.02;2200.03;211.003;743.009;148.002;124.001;59.0008;75.0008;433.007;20.0003;250.003;	179.748;707.315;2200.03;101.863;388.482;0;41.0014;18.2926;0;0;6.61316;92.721;	0.638599;0.536328;0.907075;0.484924;0.66934;0.304719;0.593844;0.550031;0.0984451;0.177845;0.593844;0.46281;	51757	1.09916	0	0	0	0.999984	0.999986	1.21909	1.17917	1.21032	1.18762
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S15_B3_1_768.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S15_B3_1_768	Peinf101Scf02008g01006	Peinf101Scf02008g01006	Peinf101Scf02008g01006.1		3028.92	2412.34	3587.44					AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR	AAAAAAAGGGGSGDEDSFVDPR2	2	2.60573e-05	0.00025866	0.00040962	0.00016129	0.000120846	0.000112587	1	0	1	1482.56	1343.19	1204.92	9469.99	0.617825	48.492	48.3118	48.6723	17.9993	48.5189	17.9506	1.36662e-05	0.000118737	0.896034	11652.1	1.85581	0.514459	0.897845	0.999738	1.01627	0.115085	181.002;982.013;1259.02;20.0003;469.006;103.001;109.001;72.0008;21.0003;419.006;85.0011;203.002;	73.8905;982.013;426.657;0;55.7064;24.7461;0;0;0;173.246;11.0242;0;	0.583263;0.740476;0.341512;0.055039;0.240951;0.417072;0.120925;0.100057;-0.28294;0.489038;0.277464;-0.39536;	51629	0.897845	0	0	0	0.999741	0.999986	1.22364	1.17917	1.21193	1.18937
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S1_A1_1_754.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S1_A1_1_754	Peinf101Scf00197g25021	Peinf101Scf00197g25021	Peinf101Scf00197g25021.1		26599.9	19121.4	16774.2					AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK	AAAAAALMMGDDMHK	AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK3	3	1.25655e-05	1.25655e-05	0.00059064	0.000166834	0.000128584	0.000112587	1	0	1	15477.9	8483.53	8445.67	12371.8	0.852482	21.8776	21.6972	22.0579	-15.2668	22.1551	-15.7683	4.58442e-05	0.000118737	0.968639	22673.1	4.1753	0.51624	0.910105	0.999987	0.684847	0.155987	185.001;4788.03;3094.01;1066.01;5255.03;10516.1;372.002;81.0005;432.003;45.0003;819.004;464.003;	19.6363;4788.03;1979.89;462.37;4915.54;5774.37;189.783;15.6094;0;15.6557;306.313;41.4537;	-0.0262507;0.954734;0.619121;0.213402;0.836306;0.781467;0.414176;0.331837;-0.129952;0.482737;0.446224;0.145681;	23272	0.910105	0	0	0	0.999954	0.999445	0.825	0.850417	0.843316	0.832733
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S2_A2_1_755.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S2_A2_1_755	Peinf101Scf00197g25021	Peinf101Scf00197g25021	Peinf101Scf00197g25021.1		20727.5	18277.7	21856.1					AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK	AAAAAALMMGDDMHK	AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK3	3	2.66375e-05	0.00011483	0.00059064	0.000151745	0.000139392	0.000112587	1	0	1	21285.4	15323.5	12582.7	12687.2	0.91573	22.1772	21.9968	22.3576	-15.2668	22.4608	-15.6868	4.58442e-05	0.000118737	0.96154	21462.1	4.68257	0.478723	0.82975	0.999885	0.304345	0.149749	169.001;4720.03;2279.01;1106.01;5034.03;11626.1;108.001;211.001;499.003;21.0001;380.002;168.001;	85.6472;4686.54;1347.33;374.314;5034.03;11564.8;36.281;69.9727;0;0;0;0;	0.537058;0.916129;0.6204;0.390033;0.952905;0.899386;0.500066;0.367137;-0.0526776;-0.251172;-0.25447;-0.115983;	23592	0.82975	0	0	0	0.999885	0.999445	0.825417	0.850417	0.846667	0.830571
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S3_A3_1_756.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S3_A3_1_756	Peinf101Scf00197g25021	Peinf101Scf00197g25021	Peinf101Scf00197g25021.1		26707.9	19776.3	20906.2					AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK	AAAAAALMMGDDMHK	AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK3	3	0.00020491	0.000687664	0.00059064	0.00014622	0.00011868	0.000112587	1	0	1	18765.3	11604.6	11050	12850.5	0.834583	22.2988	22.1186	22.4792	-15.2668	22.632	-15.776	4.58442e-05	0.000118737	0.949255	21823.1	4.63884	0.460243	0.721251	0.999311	0.777471	0.0631981	36.0003;5496.03;2660.02;1176.01;5327.03;10427.1;151.001;206.001;530.003;21.0001;814.005;176.001;	0;3716.35;2601.06;1176.01;5268.81;9780.16;0;0;0;0;313.498;0;	0.168957;0.761051;0.842164;0.814866;0.889017;0.8332;-0.150111;-0.372202;-0.0195748;0.11921;0.513054;-0.354538;	23720	0.721251	0	0	0	0.999312	0.999445	0.834583	0.850417	0.849135	0.837068
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S4_A4_1_757.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S4_A4_1_757	Peinf101Scf00197g25021	Peinf101Scf00197g25021	Peinf101Scf00197g25021.1		29075.2	19166.9	17949.5					AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK	AAAAAALMMGDDMHK	AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK3	3	5.32425e-05	0.000329641	0.00059064	0.000132135	9.75134e-05	0.000112587	1	0	1	13615.6	8889.24	10475.4	11229	0.810826	22.2984	22.1181	22.4788	-15.2668	22.5429	-15.76	4.58442e-05	0.000118737	0.918327	14595.1	4.67576	0.706891	0.826118	0.999671	2.01563	0.0485292	126.001;4630.03;2657.02;851.005;4498.02;8272.05;146.001;212.001;375.002;0;406.002;242.001;	26.6591;3130.31;2657.02;851.005;2707.28;7778.03;26.4839;0;97.8533;0;406.002;39.2224;	0.328783;0.792887;0.86463;0.866061;0.703425;0.855428;0.097258;0.355896;0.284533;0;0.823081;-0.178039;	23720	0.826118	0	0	0	0.99967	0.999445	0.830417	0.850417	0.848029	0.833404
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S5_A5_1_758.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S5_A5_1_758	Peinf101Scf00197g25021	Peinf101Scf00197g25021	Peinf101Scf00197g25021.1		23234.5	18066.2	19675.5					AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK	AAAAAALMMGDDMHK	AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK3	3	5.9077e-06	5.9077e-06	0.00059064	0.000143637	0.000106895	0.000112587	1	0	1	18078.5	12192.7	12742.3	13771.8	0.889947	22.5968	22.4165	22.7771	-15.2668	22.811	-15.5551	4.58442e-05	0.000118737	0.973477	19539.1	4.48109	0.399821	0.754516	0.999994	0.962402	0.0749775	70.0003;4507.02;1561.01;992.006;5154.03;11007.1;177.001;24.0001;548.003;0;452.003;321.002;	28.5351;3478.16;894.046;576.092;3593.26;11007.1;46.0538;0;0;0;147.392;0;	0.446797;0.756111;0.717237;0.510315;0.772151;0.970692;0.222709;-0.192308;-0.197924;0;0.112834;-0.283692;	24040	0.754516	0	0	0	0.999954	0.999445	0.825833	0.850417	0.844479	0.832959
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S6_A6_1_759.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S6_A6_1_759	Peinf101Scf00197g25021	Peinf101Scf00197g25021	Peinf101Scf00197g25021.1		14333.6	14737.7	15451.6					AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK	AAAAAALMMGDDMHK	AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK3	3	5.95646e-05	5.69347e-05	0.00059064	0.000153445	0.000115181	0.000112587	1	0	1	6865.85	7118.92	7093.24	14630.1	0.654903	22.7164	22.536	22.8969	-15.2668	22.9239	-15.5234	4.58442e-05	0.000118737	0.930966	14161.1	3.71658	0.534139	0.495795	0.999944	1.04018	0.0722619	26.0001;2934.02;1602.01;473.002;3083.02;5587.03;121.001;110.001;381.002;25.0001;324.002;252.001;	0;2214.64;1002.75;266.149;3083.02;1568.19;0;0;0;0;86.1291;0;	-0.00262078;0.530207;0.707015;0.752241;0.806693;0.532589;-0.365454;-0.0879752;-0.219699;0.435967;0.236516;0.0283017;	24168	0.495795	0	0	0	0.99994	0.999445	0.825	0.850417	0.843431	0.833088
D:\R0270\rawDIA\20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S7_A7_1_760.d	20211021_TIMS5_PRInLC1_PRI_P0096_R0270_120min_DIA_S7_A7_1_760	Peinf101Scf00197g25021	Peinf101Scf00197g25021	Peinf101Scf00197g25021.1		13204.3	10244	12037.7					AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK	AAAAAALMMGDDMHK	AAAAAALM(UniMod:35)M(UniMod:35)GDDM(UniMod:35)HK3	3	2.25637e-05	0.000104448	0.00059064	0.000150921	0.000113058	0.000112587	1	0	1	5508.68	6424.78	6754.4	14377.8	0.840182	22.8318	22.6515	23.0121	-15.2668	22.9036	-15.3419	4.58442e-05	0.000118737	0.966294	11726.1	3.17034	0.369075	0.239055	0.999897	0.940113	0.0725685	72.0004;2082.01;1045.01;409.003;2063.01;4171.02;120.001;65.0003;595.003;0;124.001;190.001;	0;752.115;88.3909;150.155;585.544;4171.02;0;3.34072;217.33;0;0;44.3238;	-0.258275;0.654808;0.476759;0.494656;0.683694;0.895576;0.195254;-0.470437;0.110066;0;0.221419;0.203586;	24296	0.239055	0	0	0	0.999896	0.999445	0.825	0.850417	0.843955	0.83274

**Comment by mgerault** [comment]
So, I checked and in fact it is simpler than expected. Your file doesn't contain the column 'First.Protein.Description' which is explicitely used in the app (cause I assumed it would always be in the report file). So the easiest solution would be to add a column named 'First.Protein.Description' to your report file, filled with NA or else.

**Comment by silasmellor** [comment]
Yep that did it! I added the column but left it empty and that seems to work fine. Thanks
