### ISSUE TITLE
missing values in iBAQ

### ISSUE THREAD

**Issue by silasmellor** [mgerault/DIAgui#2]
Hi again, after you solved the last issue with the report.tsv i now notice i get far more missing values in the iBAQ columns than the LFQ (which looks similar to what i would expect having previously processed the data). I notice that the nbTrypticPeptides column is empty for many of the accessions. Is it possible that values are missing because the script somehow does not fetch the sequence correctly from the fasta?

For instance, the two proteins below both have LFQ values, but the latter is missing iBAQ (and nbTrypticPeptides is empty for this protein)

>sp|Peinf101Ctg12514443g00001.1|Peinf101Ctg12514443g00001 Unknown protein OS=Petunia inflata OX=212142 PE=4 SV=1
MNEVRVSSPYFPESVSGGTPAANERVRKVLELERKRLQGRNI

>sp|Peinf101Ctg13044503g00001.1|Peinf101Ctg13044503g00001 acyltransferase [Capsicum annuum] OS=Petunia inflata OX=212142 PE=4 SV=1
MCSTTFSAQSIPEKITKTIICHKLIKPSSPTPPAQRWHNLSLTDQALSNSYVPVALFYTKEQLDNAFSLENPISDQLSSLLENSLSKILCSYYPYAGRFKDNTVIDCNDMGAEFYQVEINCPISFAIE

Best,
Silas

**Comment by mgerault** [comment]
Hi again,

Try to run the function 'getallseq' like this :
getallseq(pr_id = "Peinf101Ctg12185235g00001.1", bank_name = "path/to_your/FATSA_file.fasta", fasta_file = TRUE)

It should returns the peptide sequence from Peinf101Ctg12185235g00001.1 
Also, the id in your report file muste be Peinf101Ctg12185235g00001.1 and not Peinf101Ctg12185235g00001
If it returns it well, I need to dig a bit more... If so, could you send me teh fasta file you're using ?

Best regards

**Comment by silasmellor** [comment]
geallseq looks ok:
> getallseq(pr_id = "Peinf101Ctg12185235g00001.1", bank_name = "D:/R0270_flower_development_petunia/Petunia fasta files/2022-10-12-decoys-contam-Petunia_inflata_v1.0.1_proteins-pseudoUP_2.fasta.fas", fasta_file = TRUE)
Peinf101Ctg12185235g00001.1; 1/1
$Peinf101Ctg12185235g00001.1
[1] "QLIDLCINGYVDVNPHFCGTEFKVKPPKFPYDAPFTLSLKYETGEFVTDKSGTITGKWCFINDEEPFASIGSDGSM

Works fine for the one above that didn't give me iBAQ values as well! fasta attached
[2022-10-12-decoys-contam-Petunia_inflata_v1.0.1_proteins-pseudoUP_2.fasta.zip](https://github.com/mgerault/DIAgui/files/9786476/2022-10-12-decoys-contam-Petunia_inflata_v1.0.1_proteins-pseudoUP_2.fasta.zip)

**Comment by silasmellor** [comment]
Ok i realize now that the file i sent has the decoy sequences as well which might confuse the, so i just tried to run the iBAQ again with the fasta file without the decoys (not sure if it ignores the rev_sp sequences or not), but it looks pretty much the same, still missing a lot of iBAQ values (and nbTrypticPeptides).

**Comment by mgerault** [comment]
So I tried with the small example you sent me last time (only two proteins) and your fasta file and it worked, no NAs for these two iBAQ.
So I don't there is any problems with the function or your files. The only thing I can think of is that maybe some sequence contains peptide with more than 36 amino acids or less than 5. Maybe you can play with this parameter ? Otherwise I don't know what it could be...

**Comment by silasmellor** [comment]
Thanks for taking the time to try this out. I have done both default (5-36 aa) and the same settings as i used to process (7-52) and i get the same results. Could it be related to the function that calculates the number of possible tryptic peptides for a sequence from the fasta (since the nbTrypticPeptides is empty for the ones with missing values)? This is unfortunately beyond my R level to troubleshoot.

**Comment by silasmellor** [comment]
Hey again, so i did spend some time with it today and played around with running the scripts directly in R instead of using the shiny UI. My R is pretty basic so bear with me, but this is what i did and it worked (no missing nbTrypticpeptides):

```
#load report.tsv
report <- as.data.frame(data.table::fread("report.tsv", stringsAsFactors = FALSE))

#filter by q value
rep_filt <- report %>% dplyr::filter(Q.Value <= 0.01 & PG.Q.Value <= 0.01)

#run diann_maxlfq on data
rep_lfq <- diann_maxlfq(rep_filt,
                        group.header = "Protein.Group",
                        id.header = "Precursor.Id",
                        quantity.header = "Precursor.Normalised"
                        )

#some other stuff 
nc <- ncol(rep_lfq)

rep_lfq$Protein.Group <- rownames(rep_lfq)

rownames(rep_lfq) <- 1:nrow(rep_lfq)

proteins <- rep_lfq[order(rep_lfq$Protein.Group),]

proteins_1 <- proteins[,c((nc+1):ncol(proteins), 1:nc)]

## load all sequences matching IDs in report from fasta to sequence_list
sequence_list <- getallseq(pr_id = proteins_1$Protein.Group, 
                           bank_name = "Petunia_inflata_v1.0.1_proteins-pseudoUP_2.fasta", 
                           fasta_file = TRUE
)

#process iBAQ 
iBAQ <- get_iBAQ(proteins_1,
                 sequence_list,
                 ecol = 2:16,
                 peptideLength = c(7, 52),
                 nbMiscleavages = 0,
                 proteaseRegExp = getProtease(protease = "trypsin"),
                 log2_transformed = FALSE,
                 keep_original = TRUE
                 )
```

Now i honestly don't know why things aren't working when i use the shiny (i tried again and on a different PC with the same results), but maybe this makes some kind of sense to you.

**Comment by silasmellor** [comment]
Actually i just realized i needed to add the getprotease funciton code as well to the script or i would get an error (when i tried it first ttime i had that in memory and didn't realize. I added this before #process iBAQ (from your rdrr source code):

`getProtease <- function (protease = "trypsin") {
  if (protease == "trypsin") {
    return("[KR](?!P)")
  }
  else if (protease == "lys-c") {
    return("K(?!P)")
  }
  else {
    stop("Unknown Protease:", protease)
  }
}`

**Comment by mgerault** [comment]
Ok so it's weird... 
This is clearly because of your files but I don't know what it is exactly. If it still doesn't work on your side, can you send me your data on my e-mail ?

Also, you shouldn't have to add the getProtease function, it's an intern function from the package. What's the version from DIAgui you're using ? Have you tried to just uninstall and reinstall DIAgui ?

**Comment by silasmellor** [comment]
Hi Marc,
Yeah i don't know about the getProtease. I was running DIAgui off a fresh installation made on monday, so i guess it should be latest version. 

The script above does work and gives me iBAQ values for all the intensity values i have in the report - ie it seems to fill out the possible tryptic peptides correctly without missing values. For now that is fine for my use, but if you want to troubleshoot i have sent you are share link to access the files i used.

Best,
Silas

**Comment by mgerault** [comment]
ok ok
Thanks a lot, I'll check on this !

**Comment by mgerault** [comment]
So, I found my mistake ! 

Actually, to calculate iBAQ, I don't take MaxLFQ intensities (~ normalized intensity) but the sum of the raw intensities ! So you're script works but doesn't return the correct value for iBAQ.
To get the summed raw intensities, I use the diann_matrix function first and then get the iBAQ from these. I noticed a mistake from myself in the intern function pivot_aggragate when using the method 'sum'. I corrected it.

So, when you were using the shiny app, you were getting iBAQ only for some proteins and none of them were in the ten first.
Now, it should be fixed so you can update DIAgui on your computer.
If it works on your side, I will close this issue. Thanks a lot for spotting this problem !

**Comment by silasmellor** [comment]
Hey Marc,

Thanks for taking care of this, i now get everything correctly with no missing values, so the problem is fixed for me :) Good work on this app, its super useful to someone like me with only barebones R knowledge!

Good point about the normalized values, i did wonder about that when using the diann_maxlfq function, but didn't think further on it. Just from curiosity, could i use the diann_matrix function instead with the above script to get the non-normalized values?

Best,
Silas

**Comment by mgerault** [comment]
Hi Silas,

Okay, good to hear ! Yes you can use the diann_matrix function to get non normalized values.
I close this issue then 

Thanks again !

Best regards,
Marc-Antoine
