### ISSUE TITLE
Error in a unused arguments

### ISSUE THREAD

**Issue by stratei86** [mgerault/DIAgui#3]
Hi, whenever I try to run the app I get the following error

Error in a(href = "mailto:marco.gerault@gmail.com", icon("envelope"),  : 
  unused arguments (href = "mailto:marco.gerault@gmail.com", title = "Any questions, suggestions or bug report ? Feel free to send me an e-mail !")

I'm not a R expert, could you help with this?

Thanks

**Comment by mgerault** [comment]
Hello,

Can you send me the output of the function 'sessionInfo()' please ? As for now, I can't recreate this error. 
You can maybe try to update R and then reinstall DIAgui package.

**Comment by stratei86** [comment]
Hi, I reinstalled the package and now it works fine, thanks a lot!
