### ISSUE TITLE
Can't find my report.tsv file

### ISSUE THREAD

**Issue by Catball79** [mgerault/DIAgui#5]
Following youtube toturial, I firstly created an new project and moved my "report.tsv" file in it. Running DIAgui, shiny tool appeared. clicking "Select your report file", there is no any file in selection window.
![e219f847fad24d3a6f63d6dfaa92ee2](https://github.com/user-attachments/assets/1f0d331c-46a5-45db-a1d6-3cb5cc384da7)

**Comment by mgerault** [comment]
Hello,

Okay, that's unexpected. On what OS are you running R ? Did you remove the variable WD (which store the path of your working directory) from your R environment ?
It seems the shinyFile command cannot detect the path of your working directory.

**Comment by Catball79** [comment]
> Hello,
> 
> Okay, that's unexpected. On what OS are you running R ? Did you remove the variable WD (which store the path of your working directory) from your R environment ? It seems the shinyFile command cannot detect the path of your working directory.

Hi,
My OS is Windows and I didn't remove WD from my R environment. Thanks for your reply. I have finished the iBAQ quantification with R code, based on the help information of your package. Thank you! 
I got a new questween. I don't konw whether can I use the iBAQ  value to compute the FC between experimental group and control group? Some studies do that.

**Comment by mgerault** [comment]
Okay, did you try again in another folder or maybe is your working directory protected by a password ?
If the problem persist, try to uninstall DIAgui, restart your R session and reinstall it. Right now I don't see a clear cause of the problem.

Yes you can use the iBAQ for the FC calculation as long as you remember you used absolute quantification (iBAQ in that case) for this calculcation.

**Comment by Catball79** [comment]
> Okay, did you try again in another folder or maybe is your working directory protected by a password ? If the problem persist, try to uninstall DIAgui, restart your R session and reinstall it. Right now I don't see a clear cause of the problem.
> 
> Yes you can use the iBAQ for the FC calculation as long as you remember you used absolute quantification (iBAQ in that case) for this calculcation.

Thank you for your reply. Yes I have tried to change another disk and  got a same question. And there is no file encryption system enabled. Thank you very much.

There is another question based on the iBAQ. In theory, iBAQ is usually used to check the protein abundace in a same sample, LFQ to calculate the difference between several groups. You said I can use the iBAQ value to calculate FC, whether it means the iBAQ value from DIAgui is based on the normalized intensity value (such as RT-dependent). If not, should I take some normalization before FC calculation ?

**Comment by mgerault** [comment]
What is your R version and shinyFiles package version ? Try to update both and try again; most likely it is just a version problem.

iBAQ (as Top3) in DIAgui, are based on the raw inetnsity, not the normalized one. In theory, absolute quantification is already a form of normalization but you can perform another normalization after, before your FC computation. 
What I advise is to check your data after the iBAQ calculation with quality control plots like PCA, density, etc. If you see any batch effect or else, apply a normalization.

**Comment by Catball79** [comment]
R version is 4.3.2 and shinyFiles package version is 1.4.3. I'll try later.

**Comment by Catball79** [comment]
> What is your R version and shinyFiles package version ? Try to update both and try again; most likely it is just a version problem.
> 
> iBAQ (as Top3) in DIAgui, are based on the raw inetnsity, not the normalized one. In theory, absolute quantification is already a form of normalization but you can perform another normalization after, before your FC computation. What I advise is to check your data after the iBAQ calculation with quality control plots like PCA, density, etc. If you see any batch effect or else, apply a normalization.


R version is 4.3.2 and shinyFiles package version is 1.4.3. I'll try later. Thank you.

**Comment by mgerault** [comment]
Okay so something a bit weird is that the last version of shinyFiles package available on CRAN is 0.9.3 https://cran.r-project.org/web/packages/shinyFiles/index.html 
Are you sure you downloaded the right package from the right repository ?

**Comment by Catball79** [comment]
![1726746417225](https://github.com/user-attachments/assets/d0f3ad45-8d9e-4894-a294-8b190cf96594)
Sorry for the mistake i made. Yes, the shinyFiles is latest.

**Comment by mgerault** [comment]
And still it's not working after uninstalling and reinstalling everything ?

**Comment by Catball79** [comment]
I'll send the resolution method once I slove it. Thanks for your guidance.

**Comment by mgerault** [comment]
Yes I checked and I forgot to update the warning message but it did use the sum and not the maximum. You can update the package but your data will not change but just the warning message.

**Comment by Catball79** [comment]
Ok, thank you for your reply🤓



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/25/2024 17:55 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [mgerault/DIAgui] Can't find my report.tsv file (Issue #5) |

Yes I checked and I forgot to update the warning message but it did use the sum and not the maximum. You can update the package but your data will not change but just the warning message.

**Comment by Catball79** [comment]
Hi, new question
The raw intensity result from iBAQ calculation proceduer raised my interest. Because the first step is to sum the Precursor.Quantity of the same Protein.Group. First Icalculated the raw intensity result with code as followed:
raw <- diann_matrix(report, id.header = "Protein.Group",
+                     quantity.header = "Precursor.Quantity",
+                     method = "sum")
Then I checked the result by comapring the raw intensity result to the sum value of Precursor.Quantity of a specific P.G ID from the report.tsv. And question occurred. 

AOA1W2PQ72 in raw is 96455.7, however in report file, are 67157.90, 29297.80 and 48097.10 separately. Obvious raw value is not the sum value from different precursor, but the sum of 67157.90 and 29297.80.
![04faec6afef2c9156806c143ee0c041](https://github.com/user-attachments/assets/c0736976-1a8f-41b0-aea1-a0f72a2ee16c)
![a64d9ba3b1c3fa20afb674c53988802](https://github.com/user-attachments/assets/aa8646be-5d13-4008-a57d-5a171d9c8615)
![b71fb49959d7f00d6ba7c76862bce7e](https://github.com/user-attachments/assets/bfe1a682-e04a-4d83-9231-8cf7c247178c)

**Comment by mgerault** [comment]
Did you check the Q.value and the PG.Q.value of the precursor with intensity 48097.10 ? Remember that the first point of using DIAgui is to refilter the precursors from the report and recompute the quantification. If that precursor didn't fulfill the filtering criteria it was then removed from the sum.

**Comment by Catball79** [comment]
> Did you check the Q.value and the PG.Q.value of the precursor with intensity 48097.10 ? Remember that the first point of using DIAgui is to refilter the precursors from the report and recompute the quantification. If that precursor didn't fulfill the filtering criteria it was then removed from the sum.

I didn't filiter any precursors with Q.value and the PG.Q.value thresthold in today's calculation with any code. And 48097.10 won't filted even apply filter thresthold.
![c2ce2b04f19462c35c86aa935931d31](https://github.com/user-attachments/assets/772f7b29-a763-41e0-aafa-ed189bcdca59)

**Comment by mgerault** [comment]
The diann_matrix function apply by default filter, except if you set the parameters q and pg.q to 1.
But indeed that wouldn't apply to this precursor since the default cutoff are 0.01. 
I have to say this leaves me perplex, I don't have an explaination for now; do you think you could send me the full code you used and your data ?

**Comment by Catball79** [comment]
ok,

> The diann_matrix function apply by default filter, except if you set the parameters q and pg.q to 1. But indeed that wouldn't apply to this precursor since the default cutoff are 0.01. I have to say this leaves me perplex, I don't have an explaination for now; do you think you could send me the full code you used and your data ?



> The diann_matrix function apply by default filter, except if you set the parameters q and pg.q to 1. But indeed that wouldn't apply to this precursor since the default cutoff are 0.01. I have to say this leaves me perplex, I don't have an explaination for now; do you think you could send me the full code you used and your data ?

OK
[code.txt](https://github.com/user-attachments/files/17147179/code.txt)
[test_report.csv](https://github.com/user-attachments/files/17147186/test_report.csv)

**Comment by Catball79** [comment]
[code.txt](https://github.com/user-attachments/files/17147243/code.txt)
[test_report.csv](https://github.com/user-attachments/files/17147244/test_report.csv)

**Comment by mgerault** [comment]
Ok so this is indeed because a of a filtration cutoff, this one based on the column Quantity.Quality which states about the measurement quality. The default cutoff is 0.8, the Quantity.Quality of the removed precursor is 0.74 so it wasn't taken in the sum, hence the obtained intensity of 96455.7
This criteria has been added in the last version of DIAgui based on a user suggestion. Change this cutoff if you want to include it in your calculation.

**Comment by Catball79** [comment]
> Ok so this is indeed because a of a filtration cutoff, this one based on the column Quantity.Quality which states about the measurement quality. The default cutoff is 0.8, the Quantity.Quality of the removed precursor is 0.74 so it wasn't taken in the sum, hence the obtained intensity of 96455.7 This criteria has been added in the last version of DIAgui based on a user suggestion. Change this cutoff if you want to include it in your calculation.

Thank you for your rigorous approach to study !

**Comment by mgerault** [comment]
Also, I think I know why shinyFiles doesn’t find any path when you use the app.
In the code you sent me you have a line where you change your working directory with setwd. When you load DIAgui it automatically find your working directory and save its path under the variable WD. The app will take this path to load your reports. But since you change your working directory and didn't change the variable WD the app can't find anything.
When you load the package, a warning message state about this.

This is my guess for now. So to make it work either don't change your working directory or update as well the WD variable. Let me know if that worked.

**Comment by mgerault** [comment]
OK then back to square one...
